## QQ邮箱配置
spring:
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 11917558681@qq.com #发送邮件的邮箱地址
    password: botqnjozxvlyijhf
    properties.mail.smtp.port: 587
    from: 11917558681@qq.com # 发送邮件的地址，和上面username一致
    to: 11917558681@qq.com
abc:
  config: 34566
